services:
  app:
    image: vistomap:latest
    build:
      context: .
      dockerfile: Dockerfile
    container_name: vistomap
    restart: unless-stopped
    ports:
      - "3000:3000"
    env_file:
      - /etc/vistomap/.env.local
    environment:
      - NODE_ENV=production
      - HOSTNAME=0.0.0.0
